### ISSUE TITLE
Tests fail with MongoDB v1

### ISSUE THREAD

**Issue by eserte** [dagolden/Meerkat#13]
Statistical analysis suggests that the test failures are caused by MongoDB v1: http://analysis.cpantesters.org/solved?distv=Meerkat-0.011

**Comment by xdg** [comment]
Thanks for the heads up.  I'll look into it tomorrow when I'm back at work.

**Comment by xdg** [comment]
Thanks!  The tests weren't skipping properly if mongod wasn't running
due to the change to lazy connections.  I've shipped a new release to CPAN
to address that.
