### ISSUE TITLE
immortal is not handled in Meerkat::Cursor v 0.12

### ISSUE THREAD

**Issue by toddbruner** [dagolden/Meerkat#14]
in Meerkcat::Cursor, the cursor attribute seems to be missing immortal from the handlers.

    has cursor => (
        is       => 'ro',
        isa      => 'MongoDB::Cursor',
        required => 1,
        handles  => [
            qw( fields sort limit tailable skip snapshot hint ),
           qw( explain count reset has_next next info all ),
        ],
    );

this causes the code:

    $cursor->immortal(1);

to generate the error:

    Can't locate object method "immortal" via package "Meerkat::Cursor" at

Adding "immortal" to the handles array fixes this problem.

**Comment by xdg** [comment]
Thanks for the note.  As you can see in my [dashboard of neglect](http://www.dagolden.com/index.php/2613/my-github-dashboard-of-neglect/), Meerkat is in need of attention, so I hope to get to this and other issues and ship a new version in the next few weeks. (I'm currently on vacation).
