### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by toddbruner** [dagolden/Meerkat#18]
```
> # *** DEPRECATION WARNING ***
> #
> # The 'count' method will be removed in a future major release.
> # Use the 'count' method from MongoDB::Collection instead.
> #    MongoDB::Cursor::count called at inline delegation in Meerkat::Cursor for cursor->count (attribute declared in /usr/local/share/perl/5.22.1/Meerkat/Cursor.pm at line 20) line 18
> 
```

MongoDB is at v1.8.2
Meerkat is at v0.15

**Comment by xdg** [comment]
The underlying count method is deprecated.  What do you think I could do in Meerkat that would have kept you from being surprised by this?

**Comment by toddbruner** [comment]
Mr. Golden,

I understand that the underlying method is deprecated.  From your comment, am I to assume that this will break Meerkat forever once the cursor count method is removed?  If you stated that somewhere I am terribly sorry that I missed that and wasted your time by posting this error to the issue tracker.  I do wonder, if in your opinion as author of this module and as a contributor to MongoDB driver, if Meerkat could be updated to work with the next major release of the MongoDB driver.   Not even asking you to do it, I'm willing to help, but since you are most familiar with your code and the reasons for removing the count function from Mongo cursors, I am genuinely interested in your insights before attempting anything.

**Comment by xdg** [comment]
Thanks for the feedback.  I think you're right I could provide better documentation.
